- name: wazuh-server
  hosts: wazuh-server
  vars:
    wazuh_version: v4.8.1
  become: true
  roles:
    - wazuh-server-docker

- name: wazuh-manager
  hosts: wazuh-manager
  become: true
  roles:
    - wazuh-manager-vm


- name: tests
  hosts: all
  tasks:
    - name: server test
      shell: |
        curl -k -X GET "https://{{ hostvars['wazuh-server']['ansible_ssh_host'] }}:55000/" -H "Authorization: Bearer $(curl -u wazuh-wui:MyS3cr37P450r.*- -k -X POST 'https://{{ hostvars['wazuh-server']['ansible_ssh_host'] }}:55000/security/user/authenticate?raw=true')" | jq .
      register: server_response

    - name: server test result
      debug:
        msg: "{{ server_response.stdout }}"

    - name: manager test
      shell: |
        curl -k -X GET "https://{{ hostvars['wazuh-manager']['ansible_ssh_host'] }}:55000/" -H "Authorization: Bearer $(curl -u wazuh-wui:wazuh-wui -k -X POST 'https://{{ hostvars['wazuh-manager']['ansible_ssh_host'] }}:55000/security/user/authenticate?raw=true')" | jq .
      register: manager_response

    - name: manager test result
      debug:
        msg: "{{ manager_response.stdout }}"
