Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.network "public_network", ip: "192.168.100.66"
  config.vm.provider "virtualbox" do |v|
    v.name = "alma1"
    v.memory = 8192
    v.cpus = 4
  end
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end
end
