- name: Install dependencis
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - git
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Enable Docker Edge repo
  community.general.ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0

- name: Install Docker
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add user vagrant to docker group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: yes

- name: Clone wazuh docker repo
  ansible.builtin.git:
    repo: 'https://github.com/wazuh/wazuh-docker.git'
    dest: /home/vagrant/wazuh-docker
    version: v4.8.1
    depth: 1

- name: Creating certs wazuh single node
  community.docker.docker_compose_v2:
    project_src: /home/vagrant/wazuh-docker/single-node
    files: generate-indexer-certs.yml

- name: Run wazuh docker compose single node 
  community.docker.docker_compose_v2:
    project_src: /home/vagrant/wazuh-docker/single-node
    state: present

- name: Download, untar and install ngrok
  ansible.builtin.unarchive:
    src: https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
    dest: /usr/local/bin
    remote_src: yes

- name: Add ngrok authtoken
  ansible.builtin.shell: /usr/local/bin/ngrok config add-authtoken 2SVjZrBH1GHCkL73ghmSdLL5cjA_55pSui56Lcu7ZHLMCMcAg > ngrok-authtoken
  args:
    creates: /home/vagrant/ngrok-authtoken
  
- name: Run ngrok on port 443
  ansible.builtin.shell: nohup /usr/local/bin/ngrok http 443 > /var/log/ngrok.log 2>&1 &
  
- name: Get Wazuh dashboard URL
  ansible.builtin.shell: curl http://localhost:4040/api/tunnels | jq ".tunnels[0].public_url"
  register: ngrok_output

- name: Ngrok output 
  debug:
    msg: "(Ngrok) Wazuh dashboard URL: {{ ngrok_output.stdout }}"

- name: Add wazuh agent
  ansible.builtin.shell: |
    curl -o wazuh-agent-4.8.1-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-agent-4.8.1-1.x86_64.rpm \
    && sudo WAZUH_MANAGER='{{ hostvars['wazuh-server']['ansible_ssh_host'] }}' WAZUH_AGENT_NAME='server' rpm -ihv wazuh-agent-4.8.1-1.x86_64.rpm > wazuh-agent
  args:
    chdir: /home/vagrant/
    creates: /home/vagrant/wazuh-agent

- name: Start wazuh agent service
  ansible.builtin.service:
    name: wazuh-agent
    state: started
    enabled: yes
