- name: Install dependencis
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - git
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0

- name: Install Docker
  package:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes