- name: Install dependencis
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - git
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0

- name: Install Docker
  package:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add user vagrant to docker group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: yes

- name: Clone wazuh docker repo
  ansible.builtin.git:
    repo: 'https://github.com/wazuh/wazuh-docker.git'
    dest: /home/vagrant/wazuh-docker
    version: v4.8.1
    depth: 1

- name: Creating certs
  ansible.builtin.shell: docker compose -f generate-indexer-certs.yml run --rm generator
  args:
    chdir: "/home/vagrant/wazuh-docker/single-node"

- name: Run docker compose
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: "/home/vagrant/wazuh-docker/single-node"

- name: Download and Install ngrok
  ansible.builtin.shell: | 
    curl -O https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz \
    && tar xvzf ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin \
    && /usr/local/bin/ngrok config add-authtoken 2SVjZrBH1GHCkL73ghmSdLL5cjA_55pSui56Lcu7ZHLMCMcAg
  args:
    chdir: "/home/vagrant/wazuh-docker" 
  
- name: Run ngrok on port 443
  ansible.builtin.shell: nohup /usr/local/bin/ngrok http 443 > /var/log/ngrok.log 2>&1 &
  
- name: Get Wazuh dashboard URL
  ansible.builtin.shell: curl http://localhost:4040/api/tunnels | jq ".tunnels[0].public_url"
  register: ngrok_output

- name: Ngrok output 
  debug:
    msg: "(Ngrok) Wazuh dashboard URL: {{ ngrok_output.stdout }}"

- name: Add agent
  ansible.builtin.shell: |
    curl -o wazuh-agent-4.8.1-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-agent-4.8.1-1.x86_64.rpm \
    && sudo WAZUH_MANAGER='192.168.100.66' WAZUH_AGENT_NAME='server2' rpm -ihv wazuh-agent-4.8.1-1.x86_64.rpm
  args:
    chdir: "/tmp"

- name: Start wazuh agent service
  ansible.builtin.service:
    name: wazuh-agent
    state: started
    enabled: yes
